-- 코드를 입력하세요
SELECT 
    A.BOOK_ID AS BOOK_ID,
    B.AUTHOR_NAME AS AUTHOR_NAME,
    DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
    
FROM BOOK AS A 
    JOIN AUTHOR AS B 
    ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE A.CATEGORY = '경제'
ORDER BY PUBLISHED_DATE